accounts/urls.py
from django.conf.urls import url
from accounts.views import login_view, register_view, logout_view

urlpatterns = [
    url(r'^$',login_view, name = 'login'),
    url(r'^registrar/$',register_view,name = 'register'),
    url(r'^salir/$',logout_view, name = 'logout'),
]

aplicacion/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^',include('accounts.urls', namespace = 'accounts')),
    url(r'^directorio/',include('directorio.urls', namespace = 'directorio')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

directorio/urls.py
from django.conf.urls import url
from django.contrib import admin

from directorio import views
from accounts.views import update_user, edit_password

urlpatterns = [
    url(r'^$',views.home, name = 'home'),
    url(r'^nuevo/$',views.create_directorio, name = "create_dir"),
    url(r'^milista/$',views.milista_dir, name = "milista_dir"),
    url(r'^generar_acuses_milista/$',views.seleccionar_acuses_mi_lista, name="acuses_dir"),
    url(r'^(?P<id>\d+)/editar/$',views.edit_directorio, name = "edit_dir"),
    url(r'^(?P<id>\d+)/detalle/$',views.detail_directorio, name = "detail_dir"),
    url(r'^(?P<id>\d+)/eliminar/$',views.confirm_delete_directorio, name = "confirm_dir"),
    url(r'^(?P<id>\d+)/delete/$',views.delete_directorio, name = "delete_dir"),
    url(r'^(?P<id>\d+)/acuses/$',views.un_acuse, name = 'doc'),
    url(r'^crear_lista/$',views.crear_mi_lista,name = "lista_dir"),
    url(r'^crear_mis_acuses/$',views.crear_mis_acuses, name = 'crear_mis_acuses'),
    url(r'^crear_lista_general',views.crear_lista_general, name = 'crear_lista_general'),
    url(r'^acuses_generales/$',views.acuses_generales,name='acuses_generales'),
    url(r'^generar_acuses_directorio',views.seleccionar_acuses_directorio, name = "seleccion_gral_dir"),
    url(r'^(?P<id>\d+)/load_detail/$',views.load_detail, name ="load_detail"),
    url(r'^informacion/$',views.informacion2, name = "informacion"),
    url(r'^eliminado/$',views.eliminado, name = 'eliminado'),
    url(r'^agregar/(?P<id>\d+)/',views.agregar_mi_lista, name = "agregar"),
    url(r'^quitar/(?P<id>\d+)/',views.quitar_mi_lista, name = "quitar"),

    #configurcion y perfil del usuario
    url(r'^perfil/$',views.config_user, name = "user_perfil"),
    url(r'^perfil/(?P<id>\d+)/config',update_user, name = "config_perfil"),
    url(r'^perfil/(?P<id>\d+)/password', edit_password, name = "edit_password"),
    
    # Vistas de acuse
    url(r'^acuses/$',views.acuses_lista, name = "acuses_lista"),
    url(r'^nuevo/acuse',views.nuevo_acuse, name ="nuevo_acuse"),
    url(r'^(?P<id>\d+)/editar_acuse/$',views.editar_acuse, name = 'editar_acuse'),
    # url(r'^ver_acuse/$',views.ver_acuse,name = 'ver_acuse'),

    #vistas de etiquetas
    url(r'^(?P<id>\d+)/etiqueta/$',views.una_etiqueta, name = "una_etiqueta"),
    url(r'^all_etiquetas/$',views.all_etiquetas, name ="all_etiquetas"),
    url(r'^mis_etiquetas',views.mis_etiquetas, name = "mis_etiquetas"),

    #control de llibros
    url(r'^obsequios/$',views.control_obsequios, name ="control_obsequios"),
    url(r'^nuevo/obsequio$',views.new_obsequio, name = "new_obsequio"),
    url(r'^editar/obsequio/(?P<id>\d+)$',views.editar_obsequio, name = "editar_obsequio"),
    url(r'^agregar/entregados',views.agregar_entregados, name = "agregar_entregados"),

    #reportes
    url(r'^reportes/$',views.inicio_reportes, name = 'inicio_reportes'),
]

directorio/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse


class Acuse(models.Model):
    alias      = models.CharField(max_length=150, null=True)
    contenido  = models.TextField()
    update     = models.DateTimeField(auto_now=True,auto_now_add=False)
    timestamps = models.DateTimeField(auto_now=False,auto_now_add=True)
    default    = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Acuse"
        verbose_name_plural = "Acuses"

    def __str__(self):
        return self.alias

# Create your models here.
class Directorio(models.Model):
    profesion  = models.CharField(max_length=50,null=True,blank=True)
    nombre     = models.CharField(max_length=150,unique=True)
    pareja     = models.CharField(max_length=150,null=True,blank=True)
    cargo      = models.TextField(null=True,blank=True)
    direccion  = models.TextField(null=True,blank=True)
    telefono   = models.CharField(max_length=50,null=True,blank=True)
    user       = models.ForeignKey(settings.AUTH_USER_MODEL,null=True,blank=True)
    status     = models.CharField(max_length=1,default='1')
    modificado = models.CharField(max_length=150,null=True,blank=True)
    cdmx       = models.BooleanField(default=False)
    num        = models.CharField(max_length=4)
    lista      = models.BooleanField(default=False)
    acuse      = models.ForeignKey(Acuse, null=True)


    class Meta:
        verbose_name = "Directorio"
        verbose_name_plural = "Directorios"

    def __str__(self):
        return "%s%s"%(self.profesion,self.nombre)

    def get_detail_path(self):
        return reverse("directorio:detail_dir",kwargs = {'id':self.id})
    

class Obsequio(models.Model):
    nombre     = models.CharField(max_length=150)
    cantidad   = models.IntegerField()
    entregado  = models.IntegerField(default=0,null=True, blank=True)
    existencia = models.IntegerField(default=0,null=True,blank=True)
    default    = models.BooleanField(default=False)
    timestamps = models.DateTimeField(auto_now=True,auto_now_add=False)


    class Meta:
        verbose_name = "Obsequio"
        verbose_name_plural = "Obsequios"

    def __str__(self):
        return self.nombre

class Historial(models.Model):
    directorio = models.ForeignKey(Directorio)
    obsequio   = models.ForeignKey(Obsequio)
    timestamps = models.DateTimeField(auto_now=True,auto_now_add=False)
    class Meta:
        verbose_name = "Historial"
        verbose_name_plural = "Historiales"

    def __str__(self):
        return self.directorio.nombre

    

directorio/forms.py
from django import forms
from directorio.models import Directorio, Obsequio

class DirectorioForm(forms.ModelForm):
    profesion = forms.CharField(max_length=50,label='Profesión',required=False)
    pareja    = forms.CharField(max_length=150,label='Esposa(o)',required=False)
    # acuse = forms.ChoiceField(label="Acuse",required=True)
    # cdmx      = forms.BooleanField(label='CDMX',required=False)
    # opciones para el select de status
    status_opcion = (
        ('1','No Autorizado'),
        ('2','Autorizado'),
        ('3','Entregado')
    )
    status = forms.ChoiceField(choices=status_opcion,required=True)
    class Meta:
        model = Directorio
        fields = [
            'profesion',
            'nombre',
            'acuse',
            'pareja',
            'cargo',
            'direccion',
            'telefono',
            'status',
            # 'cdmx',
        ]

class ObsequioForm(forms.ModelForm):
    class Meta:
        model = Obsequio
        fields = ['nombre',
                  'cantidad',
                  'entregado',
                  'existencia',]
    

directorio/views.py
#python-docx
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt
from docx.shared import Inches

#template-docx
from templated_docs import fill_template
from templated_docs.http import FileResponse

#modelos
from directorio.models import Directorio

#django
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q

#Modelos
from directorio.models import Directorio, Obsequio, Acuse, Historial

#Formularios
from directorio.forms import DirectorioForm, ObsequioForm

# CRUD Directorio
@login_required
def home(request):
    """ 
        se requeire sesion iniciada

        Se realiza la consulta de todo el directorio(todas las personas que conforman el directorio)
        , si se llega a este punto con un parametro de busuqeda, se filtra la busqeda total, para mostrar
        las coincidencias(contenidas en la columnas profesion, nombre y cargo).
    """
    instancias = Directorio.objects.all().order_by("id")

    query = request.GET.get("q")
    if query:
        instancias = instancias.filter(Q(profesion__icontains = query)|
                                        Q(nombre__icontains = query) |
                                        Q(cargo__icontains = query) )

    contexto ={
        "directorio" : instancias,
    }
    return render(request,'home.html', contexto)

@login_required
def create_directorio(request):
    """
        se requeire sesion iniciada

        Creacion del formulario, para el registro de una nueva persona,
        se valida la informacion y se envia un mensaje de alerta.
    """
    title = ""
    form = DirectorioForm(request.POST or None)

    if form.is_valid():
        instancia = form.save(commit = False)
        instancia.user = request.user
        instancia.save()
        status = instancia.status
        messages.success(request,"!Registrado Correctamente¡")
        return HttpResponseRedirect(instancia.get_detail_path())

    contexto = {
        "title" : title,
        "form"  : form
    }
    return render(request,"form_dir.html",contexto)

@login_required
def milista_dir(request):
    """
    se requeire sesion iniciada

    se realiza la consulta de todas las personas que conforman la lista que crea el usuario, en su sesión
    , si se llega a este punto con un parametro de busqeuda, se filtra la lista y se muestran las
    coincidencias.
    """
    lista = Directorio.objects.filter(user_id__exact= request.user.id).order_by("id")

    query = request.GET.get("q")

    if query:
        lista = lista.filter(Q(profesion__icontains = query)|
                            Q(nombre__icontains = query) |
                            Q(cargo__icontains = query))
    contexto = {
        'lista' : lista
    }
    return render(request,'milista.html',contexto)

@login_required
def edit_directorio(request, id = None):
    """
        se requeire sesion iniciada

        esta vsta pide un ID de parametro, para realizar la busqueda, de la persona
        a ediar, posteriormente se crea el formulario con los datos a mostrar, se valida la informacion
        y se envia un mensjae de alerta.
    """
    persona = get_object_or_404(Directorio,id = id)
    pstatus = persona.status
    title   = "Editando a: \r %s"%persona.nombre
    form    = DirectorioForm(request.POST or None,instance = persona)
    
    if form.is_valid():
        instancia = form.save(commit = False)
        if instancia.user_id != request.user.id:
            instancia.modificado = request.user.username

        instancia.save()
        messages.success(request,"!Modificado correctamente¡")
        return HttpResponseRedirect(instancia.get_detail_path())
    contexto = {
        "title" : title,
        "form" : form
    }

    return render(request,"form_dir.html",contexto)

@login_required
def detail_directorio(request, id = None):
    """
        se reqeuire sesion iniciada

        Requeire un parametro ID para realizar la busqeuda de los detalles a mostrar de la
        persona
    """
    instancia = get_object_or_404(Directorio, id = id)
    contexto = {
        "title": "Detalles",
        "persona" :instancia,
    }

    return render(request,"detalle_dir.html",contexto)

@login_required
def confirm_delete_directorio(request,id = None):
    """
        se requiere sesion iniciada

        REquiere un parametro ID para realizar de la busqeda de la persona
        y mostrar los detalles antes de eliminar
    """
    instancia = get_object_or_404(Directorio, id = id)
    contexto = {
        "persona" : instancia,
    }
    return render(request,'confirm_delete.html',contexto)

@login_required
def delete_directorio(request, id=None ):
    """
        Se requiere sesion inicida

        requeire un parametro ID para realizar la eliminacion de
        de la persona seleccionada
    """
    instancia = get_object_or_404(Directorio, id= id)
    instancia.delete()
    return redirect('directorio:eliminado')

@login_required
def load_detail(request, id = None):
    """
    requeire sesion iniciada

    requiere un parametro ID, para mostrar los datos de una persona,
    contenido que se mostrara por AJAX jquery
    """
    instancia = get_object_or_404(Directorio, id = id)
    contexto = {
        "persona" : instancia
    }
    return render(request,"load_detail.html",contexto)

@login_required
def informacion(request):
    """ 
    No esta en funcionamiento en la aplicación
    """
    instancia  = Obsequio.objects.get(default = True)
    entregados = instancia.entregado #Directorio.objects.filter(status__exact = 3).count()
    existencia = instancia.existencia
    contexto   = {
        "obsequio" : instancia,
        "entregados" : entregados,
        "existencia"    : existencia
    }
    return render(request,"informacion.html",contexto)

@login_required
def informacion2(request):
    """
        requiere sesion iniciada

        Muestra el total de personas autorizadas y entregadas
    """
    instancia  = Obsequio.objects.get(default = True)
    entregados = Directorio.objects.filter(status__exact = 3).count()
    autorizados = Directorio.objects.filter(status__exact = 2).count()

    contexto= {
        "obsequio" : instancia,
        "entregados" : entregados,
        "autorizados" : autorizados
    }

    return render(request,"informacion.html",contexto)

@login_required
def eliminado(request):
    """
    Requiere secion iniciada

    Simplemente renderiza un template con mesaje de eliminado
    """
    return render(request,"eliminado.html")


def agregar_mi_lista(request,id = None):
    """
    Requiere un parametro ID, obtiene la persona indicada, para poder editar el user_id
    el cual sirve para que el usuario, pueda crear un alista con la cual trabajara. Esta accion se realiza a travez
    de AJAX jquery.
    """
    instancia = get_object_or_404(Directorio, id = id)
    instancia.user_id = request.user.id
    instancia.lista = True
    instancia.save()

    return HttpResponse("se añadio correctamente")

def quitar_mi_lista(request, id = None):
    """
    reqeuire un parametro ID, para relizar la busqueda de la persona,
    y poder modificar el user_id. El usuario podra reducir su lista de trabajo. Esta accion se
    realiza atravez de AJAX Jquery.
    """
    instancia = get_object_or_404(Directorio, id = id)
    instancia.lista = False
    instancia.user_id = None
    instancia.save()

    return HttpResponse("!Ya no estara en tu lista¡")

#Configuracion y perfil de usuario

@login_required
def config_user(request):
    return render(request,"configuracion_user.html")

# CRUD de Acuse
@login_required
def acuses_lista(request):
    """
        requiere sesion iniciada
        Realiza la busqueda de todos los acuses, y los muestra en lista
    """
    instancias = Acuse.objects.all()
    contexto = {
        "acuses" : instancias
    }
    return render(request,"acuses.html",contexto)

@login_required
def ver_acuse(request):
    """
    No esta en funcionamiento
    """
    instancia = Acuse.objects.get(default=True)
    contexto = {
        "acuse": instancia,
        "llamado":"ver" 
    }
    return render(request,"editar_acuse.html",contexto)

@login_required
def nuevo_acuse(request):
    """
    requiere secion inicida

    Crea un nuevo acuse, obteniendo los datos de formulario
    """
    acuse = Acuse()
    if request.POST:
        acuse.alias = request.POST.get("alias")
        acuse.contenido = request.POST.get("contenido")
        acuse.save()
        return redirect("directorio:acuses_lista")
    return render(request,"new_acuse.html")
@login_required
def editar_acuse(request, id = None):
    """
    requiere secion inicida

    REquiere un parametro ID para realizar la busqeuda de acuse,
    y poder editar los datos, obtenidos del fromulario
    """
    instancia = Acuse.objects.get(id = id)
    if request.POST:
        if request.POST.get("contenido") != "":
            instancia.contenido = request.POST.get("contenido")
            instancia.alias = request.POST.get("alias")
            instancia.save()
    
    contexto = {
        "acuse":instancia,
        "llamado" : "editar"
    }
    return render(request,"editar_acuse.html",contexto)

# vista de reportes
@login_required
def inicio_reportes(request):
    """
        crea una lista segun el boton indicado, relacionde de todos los entregados, relacion de los autorizados
        ,relacion de los no autorizados, relacion de cada acuse.
    """

    if request.POST:
        if request.POST.get("tipo") == "entregado":
            """
                Crea una relacion de las personas a las que se le entrego obsequio
            """
            instancias = Directorio.objects.filter(status__exact = 3)
            documento = Document()
            documento.add_paragraph("Relacion de Entregados")

directorio/templates/configuracion_user.html
{% extends "base.html" %}

{% block title %}
    Perfil
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col m8 offset-m2">
            <div class="section">
                <h5>Datos de Usuario</h5>
                <div class="row">
                    <div class="col m3 offset-m9"><a href='{% url "directorio:config_perfil" user.id %}' class='btn'> Editar</a></div>
                    <div class="col m12" >
                        <table class="bordered">
                            <tr><th>Nombre de usuario:</th><td>{{user}}</td></tr>
                            <tr><th>Nombre completo:</th><td>{{user.get_full_name}}</td></tr>
                            <tr><th>Contraseña:</th><td>************** {# <a href='{% url "directorio:edit_password" user.id %}'>Cambiar Contraseña</a> #}</td></tr>
                        </table>
                    </div>
                </div>
            </div>
           <!--<div class="divider"></div>
            <div class="section">
                <h5>Configuracion de mi lista</h5>
            </div>
            <div class="divider"></div>
            <div class="section">
                <h5>Configuracion de Directorio</h5>
            </div> -->
        </div>
    </div>
{% endblock content %}

directorio/templates/control_obsequios.html
{% extends "base.html" %}

{% block title %}
    Control de libros
{% endblock title %}

{% block content %}
    
    <div class="container">
        <div class="row">
            <h4>Info de Obsequios</h4>
            <div class="col m2 input-field">
                <a href="#" class="btn">Reporte</a>
            </div>
            <form id="form_agregar">
            {% csrf_token %}
                <div class="col m6">
                        
                    <select name="libro" id="libro">
                        <option value="0">Selecciona un obsequio</option>
                        {% for obsequio in  obsequios %}
                            <option value="{{obsequio.id}}">{{obsequio.nombre}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col m2">
                    <input type="number" name="cantidad" id="cantidad" min="0" placeholder="0">
                </div>
                <div class="col m2 input-field ">
                    <a href='javascript:agregar_entregados("{% url "directorio:agregar_entregados" %}")' class="btn light-blue darken-3">Guardar</a>
                </div>
            </form>
            <div class="col m12" id="infomensaje" style="text-align: center;">
                <!--aqui va el mesaje de operacion-->
            </div>
            <div class="col m12" id="tabla_obsequio">
                <table>
                    <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Cantidad Inicial</th>
                            <th>Entregados</th>
                            <th>Existencia</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for obsequio in obsequios %}
                        <tr>
                            <td><a href='{% url "directorio:editar_obsequio" obsequio.id %}'> {{obsequio.nombre}}</a></td>
                            <td>{{obsequio.cantidad}}</td>
                            <td>{{obsequio.entregado}}</td>
                            <td>{{obsequio.existencia}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

directorio/templates/home.html
{% extends "base.html" %}

{% block title %}Directorio{% endblock title %}

{% block content %}
{% load directorio_tags %}
    <div class="row">
        <form action="" method="GET">
            <div class="col m6">
                <div class="input-field">
                    <label for="Buscar">Buscar</label> 
                    <input type="text" class="" name="q" value="{{request.GET.q}}">
                </div>
            </div>
            <div class="col m6">
                <div class="input-field">
                    <button type="submit" class="btn waves-effect waves-light light-blue darken-3">
                     <i class="material-icons">search</i>
                    </button>
                    <a href='{% url "directorio:home" %}' class="btn waves-effect waves-light light-blue darken-3">Lista completa</a>
                    <!-- Dropdown Trigger -->
                    <a class='dropdown-button btn light-blue darken-3' href='#' data-activates='dropdown2'>Opciones de Word</a>
                    <!-- Dropdown Structure -->
                    <ul id='dropdown2' class='dropdown-content '>
                      <li><a href='{% url "directorio:crear_lista_general" %}' class="waves-effect waves-teal">Lista</a></li>
                      <li><a href='{% url "directorio:acuses_generales" %}' class="waves-effect waves-teal">Todos los acuses</a></li>
                      <li><a href='{% url "directorio:all_etiquetas" %}' class="waves-effect waves-teal">Todas las etiquetas</a></li>
                      <li><a href='{% url "directorio:seleccion_gral_dir" %}' class="waves-effect waves-teal">Seleccionar acuses y etiquetas autorizados</a></li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
    <div class="row">
         <div class="col m6" id="table-list" style="overflow: hidden;overflow-y: auto;">
            <table class="bordered highlight" >
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Prof.</th>
                        <th>Nombre</th>
                        {# <th>Aut.</th> #}
                        <th>Detalle</th>
                    </tr>
                </thead>
                <tbody>
                    {% for persona in directorio %}
                        {% if persona.status == "2" %}
                            <tr class=" teal accent-3">
                        {% else %}
                            {% if persona.status == "3" %}
                                <tr class="blue lighten-1">
                            {% else %}
                                <tr>
                            {% endif %}
                        {% endif %}
                            <td >{{persona.id}}</td>
                            <td >{{persona.profesion}}</td>
                            <td >{{persona.nombre}}</td>
                            <td ><label><a href='javascript:detalle("{% url "directorio:load_detail" persona.id %}");' id="link-detalle" class="btn waves-light teal darken-4">Detalles</a></label></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {# contenedor donde se mostrara el detalle  #}
        <div class="col m6" style="overflow: hidden; overflow-y: auto;" id="preview-detalle">
        </div>
    </div>
{% endblock content %} 

directorio/templates/load_detail.html
{% block content %}
<div class="row">
    <div class="col m12">
        <h5 id="mensaje-añadir" class="green-text text-darken-2"></h5>
    </div>
    <div class="col m2">
        <a href='{% url "directorio:edit_dir" persona.id %}' class="btn blue darken-4"><i class="material-icons">mode_edit</i></a>
    </div>
    {% if persona.status != "1" %}
    <div class="col m3">
        <a href='{% url "directorio:doc" persona.id%}' class="btn deep-purple">Acuse</a>
    </div>
    <div class="col m3">
        <a href='{% url "directorio:una_etiqueta" persona.id %}' class="btn amber">Etiqueta</a>
    </div>
    {% endif %}
    <div class="col m2">
        <div id="accion">
            
        </div>
        {% if not persona.lista %}
            <a href='javascript:agregar("{% url "directorio:agregar" persona.id %}")' class="btn green accent-4" id="btn-agregar"><i class="material-icons">add</i></a>
        {% else %}
            {% if persona.user_id == user.id %}
                <a href='javascript:quitar("{% url "directorio:quitar" persona.id %}")' class="btn green accent-4" id="btn-quitar"><i class="material-icons">remove</i></a>
            {% endif %}
        {% endif %}
    </div>
    <div class="col m2">
        <a href='{% url "directorio:confirm_dir" persona.id%}' class="btn red darken-4"><i class="material-icons">clear</i></a>
    </div>
    <div class="col m12" style="text-align:center; font-size: 12px;">
        <h4 align="center">{{persona.profesion}} {{persona.nombre}}</h4>
        <div class="row">
            <div class="col m12" style="font-size:14px;">
                <table class="bordered" style="text-align:left;">
                        <tr>
                            <th>Cargo:</th><td>{{persona.cargo | linebreaks}}</td>
                        </tr>
                        <tr>
                            <th>Dirección:</th><td>{{persona.direccion |linebreaks}}</td>
                        </tr>
                        <tr>
                            <th>Telefono:</th><td>{{persona.telefono}}</td>
                        </tr> 
                        <tr>
                            <th>Esposa(o):</th><td>{{persona.pareja}}</td>
                        </tr>
                        <tr>
                            <th>Pertenece a:</th><td>{{persona.user}}</td>
                        </tr>
                        {% if persona.modificado %}
                            <tr>
                                <th>Modifiado por:</th><td>{{persona.modificado}}</td>
                            </tr>
                        {% endif %}
                        {% if persona.status == "1" %}
                            <tr><th>Situación:</th><td>No Autorizado</td></tr>
                        {% else %}
                            {% if persona.status == "2" %}
                                <tr><th>Situación:</th><td>Autorizado</td></tr>
                            {% else %}
                                <tr><th>Situación:</th><td>Entregado</td></tr>
                            {% endif %}
                        {% endif %}
                        <tr>
                            <th>Acuse</th><td>{{persona.acuse.alias}}</td>
                        </tr>
                </table>
            </div>
        </div>
    </div>
</div>    
{% endblock content %}

directorio/templates/milista.html
{% extends "base.html" %}

{% block title %}
    Mi lista
{% endblock title %}

{% block content %}
   
    <div class="row">
        <form action="" method="GET">
            <div class="col m6">
                    <div class="input-field">
                        <label for="buscar">Buscar</label>
                        <input type="text" class="validate" name="q" value="{{request.GET.q}}">
                    </div>
            </div>
            <div class="col m6">
                <div class="input-field">
                    <button type="submit" class="btn light-blue darken-3"><i class="material-icons">search</i></button>
                    <a href='{% url "directorio:milista_dir" %}' class="btn light-blue darken-3">Mi Lista completa</a>
                    
                    <!-- Dropdown Trigger -->
                    <a class='dropdown-button btn light-blue darken-3' href='#' data-activates='dropdown2'>Opciones de Word</a>
                    <!-- Dropdown Structure -->
                    <ul id='dropdown2' class='dropdown-content'>
                      <li><a href='{% url "directorio:lista_dir" %}' class="">Mi Lista</a></li>
                      <li><a href='{% url "directorio:crear_mis_acuses" %}' class="">Mis Acuses</a></li>
                      <li><a href='{% url "directorio:mis_etiquetas" %}' class="">Mis etiquetas</a></li>
                      <li><a href='{% url "directorio:acuses_dir" %}' class="">Seleccionar mis acuses y etiquetas</a></li>
                    </ul>
                </div>
            </div>
        </form>
    </div>
    <div class="row">
        <div class="col m6" id="table-milista" style="overflow: hidden; overflow-y: auto;">
                <table class="bordered highlight">
                    <thead>
                        <tr>
                            <th>Profesión</th>
                            <th>Nombre</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for persona in lista %}
                            {% if persona.status == "2" %}
                                <tr class="teal accent-3">
                            {% else %}
                                {% if persona.status == "3"%}
                                    <tr class="blue lighten-1">
                                {% else %}
                                    <tr>
                                {% endif %}
                            {% endif %}
                            <td>{{persona.profesion}}</td>
                            <td>{{persona.nombre}}</td>
                            <td>
                                <label><a href='javascript:detalle("{% url "directorio:load_detail" persona.id %}");' id="link-detalle" class="btn teal darken-4">Detalles</a></label>
                            </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
        <div class="col m6" style="overflow: hidden; overflow-y: auto;" id="preview-detalle">
            
        </div>
    </div>
{% endblock content %}

directorio/templates/tabla_obsequios.html
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Cantidad Inicial</th>
            <th>Entregados</th>
            <th>Existencia</th>
        </tr>
    </thead>
    <tbody>
    {% for obsequio in obsequios %}
        <tr>
            <td><a href='{% url "directorio:editar_obsequio" obsequio.id %}'> {{obsequio.nombre}}</a></td>
            <td>{{obsequio.cantidad}}</td>
            <td>{{obsequio.entregado}}</td>
            <td>{{obsequio.existencia}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>