accounts/urls.py
from django.conf.urls import url
from accounts.views import login_view, register_view, logout_view

urlpatterns = [
    url(r'^$',login_view, name = 'login'),
    url(r'^registrar/$',register_view,name = 'register'),
    url(r'^salir/$',logout_view, name = 'logout'),
]

aplicacion/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^',include('accounts.urls', namespace = 'accounts')),
    url(r'^directorio/',include('directorio.urls', namespace = 'directorio')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

directorio/urls.py
from django.conf.urls import url
from django.contrib import admin

from directorio import views
from accounts.views import update_user, edit_password

urlpatterns = [
    url(r'^$',views.home, name = 'home'),
    url(r'^nuevo/$',views.create_directorio, name = "create_dir"),
    url(r'^milista/$',views.milista_dir, name = "milista_dir"),
    url(r'^generar_acuses_milista/$',views.seleccionar_acuses_mi_lista, name="acuses_dir"),
    url(r'^(?P<id>\d+)/editar/$',views.edit_directorio, name = "edit_dir"),
    url(r'^(?P<id>\d+)/detalle/$',views.detail_directorio, name = "detail_dir"),
    url(r'^(?P<id>\d+)/eliminar/$',views.confirm_delete_directorio, name = "confirm_dir"),
    url(r'^(?P<id>\d+)/delete/$',views.delete_directorio, name = "delete_dir"),
    url(r'^(?P<id>\d+)/acuses/$',views.un_acuse, name = 'doc'),
    url(r'^crear_lista/$',views.crear_mi_lista,name = "lista_dir"),
    url(r'^crear_mis_acuses/$',views.crear_mis_acuses, name = 'crear_mis_acuses'),
    url(r'^crear_lista_general',views.crear_lista_general, name = 'crear_lista_general'),
    url(r'^acuses_generales/$',views.acuses_generales,name='acuses_generales'),
    url(r'^generar_acuses_directorio',views.seleccionar_acuses_directorio, name = "seleccion_gral_dir"),
    url(r'^(?P<id>\d+)/load_detail/$',views.load_detail, name ="load_detail"),
    url(r'^informacion/$',views.informacion2, name = "informacion"),
    url(r'^eliminado/$',views.eliminado, name = 'eliminado'),
    url(r'^agregar/(?P<id>\d+)/',views.agregar_mi_lista, name = "agregar"),
    url(r'^quitar/(?P<id>\d+)/',views.quitar_mi_lista, name = "quitar"),

    #configurcion y perfil del usuario
    url(r'^perfil/$',views.config_user, name = "user_perfil"),
    url(r'^perfil/(?P<id>\d+)/config',update_user, name = "config_perfil"),
    url(r'^perfil/(?P<id>\d+)/password', edit_password, name = "edit_password"),
    
    # Vistas de acuse
    url(r'^acuses/$',views.acuses_lista, name = "acuses_lista"),
    url(r'^nuevo/acuse',views.nuevo_acuse, name ="nuevo_acuse"),
    url(r'^(?P<id>\d+)/editar_acuse/$',views.editar_acuse, name = 'editar_acuse'),
    # url(r'^ver_acuse/$',views.ver_acuse,name = 'ver_acuse'),

    #vistas de etiquetas
    url(r'^(?P<id>\d+)/etiqueta/$',views.una_etiqueta, name = "una_etiqueta"),
    url(r'^all_etiquetas/$',views.all_etiquetas, name ="all_etiquetas"),
    url(r'^mis_etiquetas',views.mis_etiquetas, name = "mis_etiquetas"),

    #control de llibros
    url(r'^obsequios/$',views.control_obsequios, name ="control_obsequios"),
    url(r'^nuevo/obsequio$',views.new_obsequio, name = "new_obsequio"),
    url(r'^editar/obsequio/(?P<id>\d+)$',views.editar_obsequio, name = "editar_obsequio"),
    url(r'^agregar/entregados',views.agregar_entregados, name = "agregar_entregados"),

    #reportes
    url(r'^reportes/$',views.inicio_reportes, name = 'inicio_reportes'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es-mx">
<head>
    <meta charset="UTF-8">
    <title>Directorio |{% block title %}{% endblock title %}</title>
          <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
     <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href='{% static "css/materialize.min.css" %}'  media="screen,projection"/>

    <link rel="stylesheet" type="text/css" href='{% static "css/style.css" %}'>
   
    <script type="text/javascript" src='{% static "js/jquery-3.1.0.min.js" %}'></script>
    <script type="text/javascript" src='{% static "js/materialize.min.js" %}'></script>
    <script type="text/javascript" src = '{% static "js/aplicacion.js" %}'></script>
    
    {% block ligas %}
      
    {% endblock ligas %}

    <style type="text/css">
      {% block estilo %}
        
      {% endblock estilo %}
    </style>
    <script type="text/javascript">
      {% block miscript %}
        
      {% endblock miscript %}
    </script>
</head>
<body>
  <div class="navbar-fixed">
    <nav class="light-blue darken-3">
      <div class="nav-wrapper">
        <ul class="left hide-on-med-and-down">
          <li>
            <img src='{% static "img/logo.png" %}' style="max-height: 65px;">
          </li>
          <li>
            <a href='{% url "directorio:home" %}' {% if  request.resolver_match.url_name == "home" or request.resolver_match.url_name == "seleccion_gral_dir" %}class="active"{% endif %} >Directorio</a>
          </li>
        
          <li><a href='{% url "directorio:milista_dir" %}' {% if request.resolver_match.url_name == "milista_dir" or request.resolver_match.url_name == "acuses_dir"%}class="active"{% endif %} >Mi Lista</a></li>
        
          <li><a href='{% url "directorio:create_dir" %}' {% ifequal  request.resolver_match.url_name "create_dir" %}class="active"{% endifequal %} >Nueva Persona</a></li>

          <li><a href='{% url "directorio:informacion" %}' {% ifequal  request.resolver_match.url_name "informacion" %}class="active"{% endifequal %} >Información</a></li>
          <li>
            <!-- Dropdown Trigger -->
            <a class='dropdown-button' href='#' data-activates='dropdown1'>Acuse<i class="material-icons right">arrow_drop_down</i></a>
            
            <!-- Dropdown Structure -->
            <ul id='dropdown1' class='dropdown-content '>
              {# <li><a href="#!">Nuevo</a></li> #}
              <li><a href='{% url "directorio:acuses_lista" %}'>Ver</a></li>
              <li><a href='{% url "directorio:nuevo_acuse" %}'>Nuevo</a></li>
              {# <li><a href='{% url "directorio:editar_acuse" %}'>Editar</a></li> #}
            </ul>
                  
          </li>
          {% if request.user.is_superuser %}
            <li>
              <a class='dropdown-button' href='#' data-activates='dropdown5'>Obsequios<i class="material-icons right">arrow_drop_down</i></a>
              
              <!-- Dropdown Structure -->
              <ul id='dropdown5' class='dropdown-content '>
                <li><a href='{% url "directorio:control_obsequios" %}'>Ver</a></li>
                <li><a href='{% url "directorio:new_obsequio" %}'>Nuevo</a></li>
              </ul>
            </li>
          {% endif %}

          <li><a href='{% url "directorio:inicio_reportes" %}'>Reportes</a></li>
        </ul>
        <ul class="right hide-on-med-and-down">
          <li>
            <a href="#" class="dropdown-button" data-activates="dropdown3"> Usuario: {{user}} <i class="material-icons right">arrow_drop_down</i></a>
            <ul id="dropdown3" class="dropdown-content">
              <li><a href='{% url "directorio:user_perfil" %}'>Perfil</a></li>
              {# <li><a href="#">Configuracion</a></li> #}
              <li class="divider"></li>
              <li><a href='{% url "accounts:logout" %}'>Cerrar Sesión</a></li>
            </ul>
          </li>

        </ul>
      </div>    
    </nav>
  </div>
    <div class="container-fluid" id="contenedor">
        {% block content %}
            
        {% endblock content %}
    </div>
</body>
</html>